function user(uuid) {
  return {
    _id: { $oid: "6093ece374a44a01043ae8c6" },
    uuid,
    alarms: [
      {
        alarm_type: "1",
        active: "1",
        dosage: "2",
        hour: "20",
        luminous: "1",
        medicine_type: "1",
        minute: "18",
        medical_name: "novo Remedio",
        notification_id: "945",
        period_hour: "0",
        period_min: "0",
        posBox: "5",
        quantity: "1",
        quantity_box: "10",
        monday: "0",
        third: "0",
        wednesday: "0",
        thursday: "0",
        friday: "0",
        saturday: "0",
        sunday: "1",
        sound: "1",
        times_day: "0",
        uuidAlarm: "20d30e27-c536-464a-a1c6-e6135519c780",
      },
      {
        alarm_type: "1",
        active: "1",
        dosage: "2",
        hour: "20",
        luminous: "1",
        medicine_type: "1",
        minute: "18",
        medical_name: "dipirona",
        notification_id: "945",
        period_hour: "0",
        period_min: "0",
        posBox: "5",
        quantity: "1",
        quantity_box: "10",
        monday: "0",
        third: "0",
        wednesday: "0",
        thursday: "0",
        friday: "0",
        saturday: "0",
        sunday: "1",
        sound: "1",
        times_day: "0",
        uuidAlarm: "47a0e92b-dfe1-4604-92e9-731f36f8f969",
      },
      {
        alarm_type: "1",
        active: "1",
        dosage: "2",
        hour: "20",
        luminous: "1",
        medicine_type: "1",
        minute: "18",
        medical_name: "Remedio Atualizado irmao",
        notification_id: "945",
        period_hour: "0",
        period_min: "0",
        posBox: "5",
        quantity: "1",
        quantity_box: "10",
        monday: "0",
        third: "0",
        wednesday: "0",
        thursday: "0",
        friday: "0",
        saturday: "0",
        sunday: "1",
        sound: "1",
        times_day: "0",
        uuidAlarm: "a245bd24-c806-4072-b974-51243c3de982",
      },
      {
        alarm_type: "1",
        active: "1",
        dosage: "2",
        hour: "20",
        luminous: "1",
        medicine_type: "1",
        minute: "18",
        medical_name: "so vamo",
        notification_id: "945",
        period_hour: "0",
        period_min: "0",
        posBox: "5",
        quantity: "1",
        quantity_box: "10",
        monday: "0",
        third: "0",
        wednesday: "0",
        thursday: "0",
        friday: "0",
        saturday: "0",
        sunday: "1",
        sound: "1",
        times_day: "0",
        uuidAlarm: "3ef365c8-c5ef-45c7-9f93-d8b9e9d9a89f",
      },
      {
        alarm_type: "1",
        active: "1",
        dosage: "2",
        hour: "20",
        luminous: "1",
        medicine_type: "1",
        minute: "18",
        medical_name: "ola",
        notification_id: "945",
        period_hour: "0",
        period_min: "0",
        posBox: "5",
        quantity: "1",
        quantity_box: "10",
        monday: "0",
        third: "0",
        wednesday: "0",
        thursday: "0",
        friday: "0",
        saturday: "0",
        sunday: "1",
        sound: "1",
        times_day: "0",
        uuidAlarm: "bb966e8b-8f26-4fab-b859-2ebd0fd09f11",
      },
    ],
    box: [],
    pharmaceutical: [],
    login: { cell: "1234576", email: "user@hotmail.com", password: "c2hvdw==" },
  };
}

module.exports = {
  user,
};
